### ISSUE TITLE
Error 500: "Handler dispatch failed" on contribution

### ISSUE THREAD

**Issue by nr23730** [ehrbase/ehrbase#109]
I get the following error message when trying to contribute to the repository after I did update to the develop branch:
```
{
  "error": "Handler dispatch failed; nested exception is java.lang.InternalError",
  "status": "Internal Server Error"
}
```
Then I started off with a fresh database but the error persisted.
To make sure the issue hasn't been already fixed I also tried after merging `feature/67_Inconsistent_cast` and `feature/24_validation_error_for_existing_mandatory_elements` as they might be realated but that didn't work either.

The isue seems to occur after validating the constraints because removing an element in the reference_sequence cluster leads to a `org.ehrbase.validation.constraints.wrappers.ValidationException`.

I attached the composition and the opt:
[composition.json.txt](https://github.com/ehrbase/ehrbase/files/4102942/composition.json.txt)
[MolekularpathologischerBefund.opt.txt](https://github.com/ehrbase/ehrbase/files/4102294/MolekularpathologischerBefund.opt.txt)

**Comment by Geisterfalle** [comment]
Hi Niklas,

we already found the "bad guy": https://github.com/ehrbase/ehrbase/pull/107 

Unfortunately, I had not yet the time to make this fix available on the Master. Hope that I can resolve this today!

**Comment by nr23730** [comment]
Hi Birger,

thanks for the quick reply! I meant the development branch, not master (I corrected this above). My head is on a153e4aa0973221d8f032a9377f76bd498cfdfae where you merged #107 so the error still occurs.

**Comment by Geisterfalle** [comment]
OK, in this case, @chevalleyc might have to take a closer look at this.

**Comment by nr23730** [comment]
Merging #85 solved the issue for another template that I have but not for the one mentioned above.

**Comment by nr23730** [comment]
Found it. The composition was invalid.

But I also recognized that `return=representation` outputs an invalid format. But I will report this in another issue or provide a pull request.
